name: Build Flatpak

on:
  push:
    branches:
      - "*"
      - "!master"
  workflow_dispatch:

jobs:
  build-flatpak-bundle:
    name: "Build flatpak bundle"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up Docker
      if: ${{ matrix.arch != 'x86_64' }}
      run: |
        dnf install -y docker

    - name: Set up QEMU
      if: ${{ matrix.arch != 'x86_64' }}
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ${{ github.head_ref || github.ref_name }}.flatpak
        manifest-path: ${{ github.head_ref || github.ref_name }}.yml
        cache-key: flatpak-builder-${{ github.sha }}_${{ matrix.arch }}
        upload-artifact: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.head_ref || github.ref_name }}.flatpak
        path: ${{ github.head_ref || github.ref_name }}.flatpak
        retention-days: 0

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Create release
      id: release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.head_ref || github.ref_name }}_${{ steps.date.outputs.date }}
        release_name: ${{ github.head_ref || github.ref_name }}
        draft: false
        prerelease: false
